CREATE TABLE [dbo].[Contact_Custom]
(
[SSB_CRMSYSTEM_ACCT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SSB_CRMSYSTEM_CONTACT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[new_ssbcrmsystemssidwinner] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ssbcrmsystemSSIDWinnerSourceSystem] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_Ids] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimCustIDs] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountID] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_category] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_number] [nvarchar] (2500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ssb_NewBusinessLead] [date] NULL,
[new_ssb_GroupSalesLead] [date] NULL,
[new_ssb_EloquaTicketInformation] [date] NULL,
[new_ssb_EloquaPromotionalInformation] [date] NULL,
[new_ssb_EloquaPremiumInformation] [date] NULL,
[new_ssb_EloquaFormSubmission] [date] NULL,
[new_ssb_EmailActivity] [datetime] NULL,
[new_ssb_NewPremiumLead] [date] NULL,
[ownerid] [uniqueidentifier] NULL,
[str_clientpremiumsalesperson] [uniqueidentifier] NULL,
[new_groupssalesperson] [uniqueidentifier] NULL,
[new_TMSecondaryContact] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_TMOtherContact] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridtype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mobilephone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ssb_HondaGroupSalesLead] [date] NULL,
[str_clientrecenteloquainfo] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientrecenteloquadate] [datetime] NULL,
[new_distancefromarena] [decimal] (28, 0) NULL,
[new_ssb_EmailAddress2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ssb_SuiteInterest_yesno] [bit] NULL,
[new_ssb_SingleGameTicketInterest_yesno] [bit] NULL,
[new_ssb_MiniPlanInterest_yesno] [bit] NULL,
[new_ssb_GroupInterest_yesno] [bit] NULL,
[new_ssb_AttendancePercentage] [int] NULL,
[new_ssb_ResoldTicketsPercentage] [int] NULL,
[new_ssb_TransferredTicketsPercentage] [int] NULL,
[new_ssb_unusedticketspercentage] [int] NULL,
[new_ssb_donatedticketspercentage] [int] NULL,
[new_ssb_ExchangedTicketsPercentage] [int] NULL,
[new_ssb_LastDedicationLogin] [date] NULL,
[new_ssb_DedicationPointsEarned] [int] NULL,
[new_ssb_DedicationPointsRemaining] [int] NULL,
[parentcustomerid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomeridtype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ssb_SuiteInterest_Date] [date] NULL,
[new_ssb_SingleGameTicketInterest_Date] [date] NULL,
[new_ssb_MiniPlanInterest_Date] [date] NULL,
[new_ssb_GroupInterest_Date] [date] NULL,
[new_ssb_SeasonTicketInterest_Date] [date] NULL,
[str_clientpremiumserviceperson] [uniqueidentifier] NULL
)
GO
ALTER TABLE [dbo].[Contact_Custom] ADD CONSTRAINT [PK_Contact_Custom] PRIMARY KEY CLUSTERED  ([SSB_CRMSYSTEM_CONTACT_ID])
GO
